services:
  listen_auth:
    build:
      context: .
      dockerfile: listen_auth/dockerfile

    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - API_SECRET_KEY=some-secret-key

    env_file:
      - host.env

    command: bash -c " python app/manage.py migrate && python app/manage.py runserver "
    ports:
      - "3000:3000"
    
  listen_api:
    build:
      context: .
      dockerfile: listen_api/dockerfile

    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - DB_HOST=listendb
      - DB_PORT=5432
      - DB_NAME=listendb
      - DB_USER=owner
      - DB_PASSWORD=password
      - AUTH_SERVER=listen_auth:3000
      - API_SECRETE_KEY=some-secret-key
    
    env_file:
      - host.env

    command: bash -c " python app/manage.py migrate && python app/manage.py runserver "
    ports:
      - "5000:5000"

    depends_on:
      - listendb
      - listen_auth
    
    restart: always
    
  listendb:
    image: postgres:latest
    environment:
      - POSTGRES_USER=owner
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=listendb
    ports:
      - "5432:5432"

  listen_gateway:
    build: 
      context: .
      dockerfile: listen_gateway/dockerfile
    environment:
      - AUTH_HOST=listen_auth
      - AUTH_PORT=3000
      - API_HOST=listen_api
      - API_PORT=5000
    
    env_file:
      - host.env

    links:
      - listen_auth
      - listen_api

    ports:
      - "80:80"

    depends_on:
      - listen_auth
      - listen_api