FROM nginx:latest

# COPY /listen_gateway/nginx.conf etc/nginx
COPY /listen_gateway/templates/default.conf.template etc/nginx/templates/default.conf.template

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]